### ISSUE TITLE
Remove _workspace

### ISSUE THREAD

**Issue by PeterDaveHello** [github/lfs-test-server#18]
There is no reason to put them into git repo, 'cause they come from other projects, you don't edit it or modify it in this project, no reason to track and waste history and space, what do you think?

Ref:
http://stackoverflow.com/questions/26334220/should-i-commit-godeps-workspace-or-is-godeps-json-enough

**Comment by tomzhang** [comment]
there is a bug that i found when i compile lfs-test-server in my local environment (golang version 1.3.3 ).
for code snippet mgmt.go both line 53 and 155 should change "r *Http.Request " to  "r *request"  accoring  to the golang http module documents : "func (r *Request) BasicAuth() (username, password string, ok bool)"

**Comment by rubyist** [comment]
@PeterDaveHello our standard practice is to fully vendor our dependencies. This has a few advantages for us: it allows build and deploy systems to not depend on third party systems,  if the referenced repositories are removed we can still build and deploy, and it allows us to see what changed in the dependencies when they're updated without having to go track them down elsewhere. It isn't a terribly big deal in this test repo to go one way or the other, that's just the general way that we work on our production code and it carries over here.

@tomzhang I think you're seeing that error because compiling this code will require go 1.4. The `BasicAuth` function was not present in go 1.3 or earlier. I will add a note to the build instructions about Go version requirements, thanks!
