### ISSUE TITLE
Clarifying .gitconfig setup and LFS url

### ISSUE THREAD

**Issue by yunspace** [github/lfs-test-server#42]
Hi, I'm have some confusions in regards to the setup instructions (similar to #23), but thought it's better to start a new issue which can be answered and closed off.

1. Which `.gitconfig` file am I meant to update? Is it:
  - the root `~/.gitconfig` file
  - the local repository `.git/config` file
  - or a new `.gitconfig` file which I need to create inside my repository (which doesn't seem to be part of git convention?)

2. What is the correct LFS url I'm supposed to use?
  - `lfs-test-server` README says  `[lfs] url = "https://host:port/jimdoe/lfsrepo`
  - If I go to `https://localhost:9999/mgmt` it says `[lfs] url = "https://host:port/user/repo`
  - Other users seem to be using `[lfs] url = "https://host:port/user/`
  - If I look at alternative implementations such as `git-lfs-s3`, it says to use [lfs]
    url = "http://yourserver.com"

I was able to get the lfs-test-server up and running, but then ran into other issues with the server hanging when I tried to do git-lfs push. Please confirm the above points 1 and 2 and I will re-visit my setup before looking into the hanging issue. Many thanks!

**Comment by rubyist** [comment]
Hi, sorry for the delayed response. When setting up a custom Git LFS endpoint, you'd likely use a `.gitconfig` in your repository. You can use `~/.gitconfig` or `.git/config` but those will not "travel" with the repo, and each person who clones the repo will have to manually set theirs up.

For the URL, either `https://host:port/jimdoe/lfsrepo` should be fine. The mgmt interface just has a generic `/user/repo`. I think I'm going to modify that, because it's confused people before. What's more confusing is that with this test server implementation, the `/user/repo` part of the URL is pretty much ignored. I think it's time for us to just remove that part altogether.

Thanks for the feedback. I'm going to revisit the docs and url configuration and make that less confusing. Feel free to close this issue if your questions have been addressed.

**Comment by yunspace** [comment]
thanks for the clarification. Will try as you have suggested. Closing.
